name: Mischief and Shenanigans
favicon: null
layout_spectrum: 0.64453
typography_spectrum: 0.60626
title: Lifestyles of the Insane
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d2d2b'
    - '#c3d3c6'
    - '#5f5e5c'
    - '#a09f9b'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
